services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "AwadMSsqlServer90!"
    volumes:
      - ./sql_data:/var/opt/mssql

    restart: unless-stopped
