version: 7
groups:
  - id: ca0da75a-ac14-4448-be04-b5161c95a58c
    name: 'AAA Tokens '
    defaults:
      ssh:
        type: ssh
        options:
          algorithms: {}
          input: {}
        color: '#e00'
configSync:
  parts: {}
hotkeys:
  toggle-window: []
  copy-current-path: []
  ctrl-c:
    - Ctrl-C
  copy:
    - Ctrl-Shift-C
  paste:
    - Ctrl-Shift-V
    - Shift-Insert
  select-all:
    - Ctrl-Shift-A
  clear:
    - Ctrl-L
  zoom-in:
    - Ctrl-=
    - Ctrl-Shift-=
  zoom-out:
    - Ctrl--
    - Ctrl-Shift--
  reset-zoom:
    - Ctrl-0
  home:
    - Home
  end:
    - End
  previous-word:
    - Ctrl-Left
  next-word:
    - Ctrl-Right
  delete-previous-word:
    - Ctrl-Backspace
  delete-line:
    - Ctrl-Shift-Backspace
  delete-next-word:
    - Ctrl-Delete
  search:
    - Ctrl-Shift-F
  pane-focus-all:
    - Ctrl-Shift-I
  focus-all-tabs:
    - Ctrl-Alt-Shift-I
  scroll-to-top:
    - Ctrl-PageUp
  scroll-up:
    - Alt-PageUp
  scroll-down:
    - Alt-PageDown
  scroll-to-bottom:
    - Ctrl-PageDown
  restart-telnet-session: []
  restart-ssh-session: []
  launch-winscp: []
  settings-tab: {}
  settings:
    - Ctrl-,
  serial:
    - Alt-K
  restart-serial-session: []
  new-tab:
    - Ctrl-N
  new-window:
    - Ctrl-Shift-N
  profile: {}
  profile-selectors: {}
  toggle-fullscreen:
    - F11
  close-tab:
    - Ctrl-Shift-W
  reopen-tab:
    - Ctrl-Shift-Z
  toggle-last-tab: []
  rename-tab:
    - Ctrl-Shift-R
  next-tab:
    - Ctrl-Shift-Right
    - Ctrl-Tab
  previous-tab:
    - Ctrl-Shift-Left
    - Ctrl-Shift-Tab
  move-tab-left:
    - Ctrl-Shift-PageUp
  move-tab-right:
    - Ctrl-Shift-PageDown
  rearrange-panes: []
  duplicate-tab: []
  restart-tab: []
  reconnect-tab: []
  disconnect-tab: []
  explode-tab:
    - Ctrl-Shift-.
  combine-tabs:
    - Ctrl-Shift-,
  tab-1:
    - Alt-1
  tab-2:
    - Alt-2
  tab-3:
    - Alt-3
  tab-4:
    - Alt-4
  tab-5:
    - Alt-5
  tab-6:
    - Alt-6
  tab-7:
    - Alt-7
  tab-8:
    - Alt-8
  tab-9:
    - Alt-9
  tab-10:
    - Alt-0
  tab-11: []
  tab-12: []
  tab-13: []
  tab-14: []
  tab-15: []
  tab-16: []
  tab-17: []
  tab-18: []
  tab-19: []
  tab-20: []
  split-right:
    - Ctrl-Shift-S
  split-bottom:
    - Ctrl-Shift-D
  split-left: []
  split-top: []
  pane-nav-right:
    - Ctrl-Alt-Right
  pane-nav-down:
    - Ctrl-Alt-Down
  pane-nav-up:
    - Ctrl-Alt-Up
  pane-nav-left:
    - Ctrl-Alt-Left
  pane-nav-previous:
    - Ctrl-Alt-[
  pane-nav-next:
    - Ctrl-Alt-]
  pane-nav-1: []
  pane-nav-2: []
  pane-nav-3: []
  pane-nav-4: []
  pane-nav-5: []
  pane-nav-6: []
  pane-nav-7: []
  pane-nav-8: []
  pane-nav-9: []
  pane-maximize:
    - Ctrl-Alt-Enter
  pane-increase-vertical: []
  pane-decrease-vertical: []
  pane-increase-horizontal: []
  pane-decrease-horizontal: []
  close-pane: []
  switch-profile:
    - Ctrl-Alt-T
  profile-selector:
    - Ctrl-Shift-E
  command-selector:
    - Ctrl-Shift-P
terminal:
  searchOptions: {}
  colorScheme:
    name: deep
    foreground: '#cdcdcd'
    background: '#000000'
    cursor: '#d0d0d0'
    colors:
      - '#000000'
      - '#d11600'
      - '#37c32c'
      - '#e3c421'
      - '#5c6bfd'
      - '#dd5be5'
      - '#6eb4f2'
      - '#e0e0e0'
      - '#535353'
      - '#f4152c'
      - '#01ea10'
      - '#ffee1d'
      - '#8cb0f8'
      - '#e056f5'
      - '#67ecff'
      - '#f4f4f4'
  customColorSchemes: []
  profile: local:usrbinzsh
  cursor: underline
ssh:
  knownHosts:
    - host: 18.102.82.120
      port: 22
      type: ecdsa-sha2-nistp256
      digest: ggUN8ADeuIYWPmKUjZ69X15OC+9eEzhwwynEZxPN2Mo=
    - host: 18.102.105.95
      port: 22
      type: ecdsa-sha2-nistp256
      digest: Jif4wgiTrfYzRor7TLk4SIgbMUtqkGqg6Wm8DlspgaA=
    - host: 5.tcp.eu.ngrok.io
      port: '12898'
      type: ecdsa-sha2-nistp256
      digest: vWnTAKQPvv0q/s8ihfs6KlV1M3FYZYAdNNrDBMWxtVI=
    - host: 15.161.174.115
      port: 22
      type: ecdsa-sha2-nistp256
      digest: FspOpjhSUOvMbiPr41IVcXG/OawIQeuWM0sfAvVcGKM=
    - host: 2.tcp.eu.ngrok.io
      port: '11882'
      type: ecdsa-sha2-nistp256
      digest: w72m2A8Vt4epBMLr55RDzlFfU5Y0jtDqV5yzcZCbPFs=
clickableLinks: {}
accessibility: {}
appearance:
  css: |
    /* * { color: blue !important; } */
hacks: {}
providerBlacklist: []
commandBlacklist: []
language: en-US
enableAnalytics: false
enableWelcomeTab: false
pluginBlacklist: []
profileDefaults:
  ssh:
    disableDynamicTitle: true
profileBlacklist: []
profiles:
  - name: AAA Tokens Backend
    options:
      host: 18.102.82.120
      user: ubuntu
      privateKeys:
        - /home/awad/.ssh/.keys/keypair-aaatokens.pem
      algorithms:
        hmac:
          - hmac-sha1
          - hmac-sha1-etm@openssh.com
          - hmac-sha2-256
          - hmac-sha2-256-etm@openssh.com
          - hmac-sha2-512
          - hmac-sha2-512-etm@openssh.com
        kex:
          - curve25519-sha256
          - curve25519-sha256@libssh.org
          - diffie-hellman-group-exchange-sha256
          - diffie-hellman-group14-sha256
          - diffie-hellman-group15-sha512
          - diffie-hellman-group16-sha512
          - diffie-hellman-group17-sha512
          - diffie-hellman-group18-sha512
          - ecdh-sha2-nistp256
          - ecdh-sha2-nistp384
          - ecdh-sha2-nistp521
        cipher:
          - aes128-ctr
          - aes128-gcm
          - aes128-gcm@openssh.com
          - aes192-ctr
          - aes256-ctr
          - aes256-gcm
          - aes256-gcm@openssh.com
        serverHostKey:
          - ecdsa-sha2-nistp256
          - ecdsa-sha2-nistp384
          - ecdsa-sha2-nistp521
          - rsa-sha2-256
          - rsa-sha2-512
          - ssh-ed25519
          - ssh-rsa
      input: {}
      scripts: []
      forwardedPorts: []
    id: ssh:custom:AAA-Tokens-Backend:5ba79fa8-33ab-4a15-9aa3-fb5007eb91f4
    group: ca0da75a-ac14-4448-be04-b5161c95a58c
    color: '#EE0000'
    terminalColorScheme:
      name: Red Alert
      foreground: '#ffffff'
      background: '#762423'
      cursor: '#ffffff'
      colors:
        - '#000000'
        - '#d62e4e'
        - '#71be6b'
        - '#beb86b'
        - '#489bee'
        - '#e979d7'
        - '#6bbeb8'
        - '#d6d6d6'
        - '#262626'
        - '#e02553'
        - '#aff08c'
        - '#dfddb7'
        - '#65aaf1'
        - '#ddb7df'
        - '#b7dfdd'
        - '#ffffff'
    type: ssh
  - name: Frontend Production
    type: ssh
    group: ca0da75a-ac14-4448-be04-b5161c95a58c
    options:
      host: 15.161.174.115
      user: ubuntu
      privateKeys:
        - /home/awad/.ssh/.keys/keypair-aaatokens.pem
      algorithms:
        hmac:
          - hmac-sha1
          - hmac-sha1-etm@openssh.com
          - hmac-sha2-256
          - hmac-sha2-256-etm@openssh.com
          - hmac-sha2-512
          - hmac-sha2-512-etm@openssh.com
        kex:
          - curve25519-sha256
          - curve25519-sha256@libssh.org
          - diffie-hellman-group-exchange-sha256
          - diffie-hellman-group14-sha256
          - diffie-hellman-group15-sha512
          - diffie-hellman-group16-sha512
          - diffie-hellman-group17-sha512
          - diffie-hellman-group18-sha512
          - ecdh-sha2-nistp256
          - ecdh-sha2-nistp384
          - ecdh-sha2-nistp521
        cipher:
          - aes128-ctr
          - aes128-gcm
          - aes128-gcm@openssh.com
          - aes192-ctr
          - aes256-ctr
          - aes256-gcm
          - aes256-gcm@openssh.com
        serverHostKey:
          - ecdsa-sha2-nistp256
          - ecdsa-sha2-nistp384
          - ecdsa-sha2-nistp521
          - rsa-sha2-256
          - rsa-sha2-512
          - ssh-ed25519
          - ssh-rsa
      input: {}
      forwardedPorts: []
      scripts: []
    color: '#EE0000'
    terminalColorScheme:
      name: Red Sands
      foreground: '#d7c9a7'
      background: '#7a251e'
      cursor: '#ffffff'
      colors:
        - '#000000'
        - '#ff3f00'
        - '#00bb00'
        - '#e7b000'
        - '#0072ff'
        - '#bb00bb'
        - '#00bbbb'
        - '#bbbbbb'
        - '#555555'
        - '#bb0000'
        - '#00bb00'
        - '#e7b000'
        - '#0072ae'
        - '#ff55ff'
        - '#55ffff'
        - '#ffffff'
    id: ssh:custom:Frontend-Production:8c738a08-fb97-4fd5-8ca4-7ee79546d91e
  - type: ssh
    group: ca0da75a-ac14-4448-be04-b5161c95a58c
    options:
      host: 18.102.105.95
      user: ubuntu
      privateKeys:
        - /home/awad/.ssh/.keys/keypair-aaatokens.pem
      algorithms:
        hmac:
          - hmac-sha1
          - hmac-sha1-etm@openssh.com
          - hmac-sha2-256
          - hmac-sha2-256-etm@openssh.com
          - hmac-sha2-512
          - hmac-sha2-512-etm@openssh.com
        kex:
          - curve25519-sha256
          - curve25519-sha256@libssh.org
          - diffie-hellman-group-exchange-sha256
          - diffie-hellman-group14-sha256
          - diffie-hellman-group15-sha512
          - diffie-hellman-group16-sha512
          - diffie-hellman-group17-sha512
          - diffie-hellman-group18-sha512
          - ecdh-sha2-nistp256
          - ecdh-sha2-nistp384
          - ecdh-sha2-nistp521
        cipher:
          - aes128-ctr
          - aes128-gcm
          - aes128-gcm@openssh.com
          - aes192-ctr
          - aes256-ctr
          - aes256-gcm
          - aes256-gcm@openssh.com
        serverHostKey:
          - ecdsa-sha2-nistp256
          - ecdsa-sha2-nistp384
          - ecdsa-sha2-nistp521
          - rsa-sha2-256
          - rsa-sha2-512
          - ssh-ed25519
          - ssh-rsa
      input: {}
      forwardedPorts: []
      scripts: []
    name: Staging
    color: '#EE00EE'
    id: ssh:custom:Staging:a228a697-eb70-45d4-840a-a19d430e403a
  - type: local
    options:
      command: /usr/bin/zsh
      args:
        - '--login'
      env: {}
    name: Local
    id: local:custom:Local:827d12a1-5309-4bbd-a149-60154877108d
  - type: ssh
    name: awad (.ssh/config)
    options:
      host: 5.tcp.eu.ngrok.io
      port: '12898'
      user: awad
      auth: null
      password: null
      privateKeys: []
      keepaliveInterval: 5000
      keepaliveCountMax: 10
      readyTimeout: null
      x11: false
      skipBanner: false
      jumpHost: null
      agentForward: false
      warnOnClose: null
      algorithms:
        hmac:
          - hmac-sha1
          - hmac-sha1-etm@openssh.com
          - hmac-sha2-256
          - hmac-sha2-256-etm@openssh.com
          - hmac-sha2-512
          - hmac-sha2-512-etm@openssh.com
        kex:
          - curve25519-sha256
          - curve25519-sha256@libssh.org
          - diffie-hellman-group-exchange-sha256
          - diffie-hellman-group14-sha256
          - diffie-hellman-group15-sha512
          - diffie-hellman-group16-sha512
          - diffie-hellman-group17-sha512
          - diffie-hellman-group18-sha512
          - ecdh-sha2-nistp256
          - ecdh-sha2-nistp384
          - ecdh-sha2-nistp521
        cipher:
          - aes128-ctr
          - aes128-gcm
          - aes128-gcm@openssh.com
          - aes192-ctr
          - aes256-ctr
          - aes256-gcm
          - aes256-gcm@openssh.com
        serverHostKey:
          - ecdsa-sha2-nistp256
          - ecdsa-sha2-nistp384
          - ecdsa-sha2-nistp521
          - rsa-sha2-256
          - rsa-sha2-512
          - ssh-ed25519
          - ssh-rsa
      proxyCommand: null
      forwardedPorts: []
      scripts: []
      socksProxyHost: null
      socksProxyPort: null
      httpProxyHost: null
      httpProxyPort: null
      reuseSession: true
      input:
        backspace: backspace
    id: ssh:custom:awad-(.sshconfig):ba4071fe-851b-4b40-98b3-58471d93a7a4
    group: Imported from .ssh/config
    icon: ''
    color: ''
    disableDynamicTitle: true
    behaviorOnSessionEnd: auto
docker: {}
backgroundPlugin:
  backgroundEnabled: true
  backgroundPath: /home/awad/Pictures/wallpapers/tabby-wallpaper.jpg
  backgrounds: []
  backgroundShowType: float
  backgroundFloatSize: 1000
  backgroundFloatX: -300
  backgroundOpacity: 59
  backgroundBrightness: 153
  backgroundContrast: 368
  backgroundFloatY: -200
