services:
    db:
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: password
        ports:
            - "3306:3306"
        volumes:
            - ./mysql_data:/var/lib/mysql

